ADDED: -x @. Also remove underscores and spaces from tags.

diff --git a/moufoplot b/moufoplot
--- a/moufoplot
+++ b/moufoplot
@@ -132,6 +132,48 @@ gen_names()
     fi
 }
 
+# Convert Space Separated Values -> Comma Separated Values
+convert_ssv2csv()
+{
+    local ssv=${1}
+    local value
+    local csv
+    for value in ${ssv};do
+	csv="${csv},${value}"
+    done
+    RETVAL=`echo ${csv}|sed 's/.\(.*\)/\1/'`
+}
+
+get_all_dir()
+{
+    local DIR=$1
+    local all=`ls -1 ${DIR}`
+    convert_ssv2csv "${all}"
+}
+
+get_all_file()
+{
+    local DIR=$1
+    local all=`cat ${DIR} | egrep -o ".+:" | sed 's/://'`
+    convert_ssv2csv "${all}"
+}
+
+# Usage get_all DIR
+# Return all variables in DIR
+get_all()
+{
+    local DIR=$1
+    if [ -d ${DIR} ];then
+	get_all_dir ${DIR}
+    elif [ -f ${DIR} ];then
+	get_all_file ${DIR}
+    else
+	printf "ERROR: ${DIR} not a file or directory.\n"
+	exit 1
+   fi
+}
+
+
 # Input: DIR MATCHES
 # Output: The number that matches
 # Example: get_match i2 jpeg d1 opt2
@@ -1967,6 +2009,22 @@ parse_offsets()
     fi
 }
 
+# Remove unwanted characters from tags like: '_' ' ' etc.
+fix_tags()
+{
+    local csv=${1}
+    local value
+    local csv_fixed
+    set_ifs ","
+    for value in ${csv}; do
+	local value_fixed=`echo ${value}|sed 's/ /-/g' | sed 's/_/-/g'`
+	csv_fixed="${csv_fixed},${value_fixed}"
+    done
+    reset_ifs
+    csv_fixed=`echo ${csv_fixed} | sed 's/.\(.*\)/\1/'`
+    RETVAL=${csv_fixed}
+}
+
 parse_tags()
 {
     # Custom Labels (TAGS)
@@ -1977,8 +2035,8 @@ parse_tags()
 	x_tags=${x_vals}
     fi
     for x in ${x_tags}; do
-	local x_nospaces=`echo ${x}|sed 's/ /-/g'` # Remove spaces
-	xtags_array[${xi}]="${x_nospaces}"
+	fix_tags "${x}"		# Remove spaces, underscores
+	xtags_array[${xi}]="${RETVAL}"
 	xi=$((xi+1))
     done
 
@@ -1989,8 +2047,8 @@ parse_tags()
 	y_tags=${y_vals}
     fi
     for y in ${y_tags}; do
-	local y_nospaces=`echo ${y}|sed 's/ /-/g'` # Remove spaces
-	ytags_array[${yi}]="${y_nospaces}"
+	fix_tags "${y}"		# Remove spaces, underscores
+	ytags_array[${yi}]="${RETVAL}"
 	yi=$((yi + 1))
     done
 
@@ -2001,8 +2059,8 @@ parse_tags()
 	z_tags=${z_vals}
     fi
     for z in ${z_tags}; do
-	local z_nospaces=`echo ${z}|sed 's/ /-/g'` # Remove spaces
-	ztags_array[${zi}]="${z}"
+	fix_tags "${z}"		# Remove spaces, underscores
+	ztags_array[${zi}]="${RETVAL}"
 	zi=$((zi + 1))
     done
     reset_ifs
@@ -2020,11 +2078,34 @@ parse_vals()
 	    # y_vals=${x_vals_sv}
     # 	fi
     # fi
-    
 
-    x_array=${x_vals}
-    y_array=${y_vals}
-    z_array=${z_vals}
+
+    # Support -x @ / -y @ / -z @ 
+    # NOTE: -x * looks tempting but bash expands it, so -x "*" should be used 
+    #       this could lead to hard-to-spot errors
+    if [ "${x_vals}" == "@" ];then
+	get_all ${DIR}
+	x_array=${RETVAL}
+	x_vals=${RETVAL}
+    else
+	x_array=${x_vals}
+    fi
+    if [ "${y_vals}" == "@" ];then
+	get_all ${DIR}
+	y_array=${RETVAL}
+	y_vals=${RETVAL}
+    else
+	y_array=${y_vals}
+    fi
+    if [ "${z_vals}" == "@" ];then
+	get_all ${DIR}
+	z_array=${RETVAL}
+	z_vals=${RETVAL}
+    else
+	z_array=${z_vals}
+    fi
+
+
 
     if [ "${z_array}" == "" ];then
 	z_array="NO-ZAXIS"
