ADDED: --linetype, --pnttype, moufoplot and gnuplot version in the appended text.

diff --git a/moufoplot b/moufoplot
--- a/moufoplot
+++ b/moufoplot
@@ -619,7 +619,19 @@ gp_line_options()
 	fi
 
 	local color=${color_array[$cmn]}
-	plot_cmd="${plot_cmd} \"${data_file}\" using ${cmn}:xtic(1) with linespoints title columnheader(${cmn}) lw ${line_width} ps ${point_size} lc rgb \"${color}\","
+
+	if [ "${point_type}" != "" ];then
+	    local pnt_type="pt ${point_type_array[${xi}]}"
+	else
+	    local pnt_type=""
+	fi
+	if [ "${line_type}" != "" ];then
+	    local ln_type="lt ${line_type_array[${xi}]}"
+	else
+	    local ln_type=""
+	fi
+
+	plot_cmd="${plot_cmd} \"${data_file}\" using ${cmn}:xtic(1) with linespoints title columnheader(${cmn}) lw ${line_width} ps ${point_size} ${pnt_type} ${ln_type} lc rgb \"${color}\","
 	cmn=$((cmn+1))
 	xi=$((${xi} + 1))
     done
@@ -1365,7 +1377,6 @@ sanity_checks()
 	point_size=`echo "1 + ${line_width}/8" |bc -l` # Default point size
     fi
 
-
     # offsets
     if [ "${x_label_offset}" != "" ];then
 	is_number ${x_label_offset}
@@ -1828,7 +1839,46 @@ parse_zmask()
     fi
 }
 
+parse_pnttype()
+{
+    if [ "${point_type}" != "" ];then
+	local p
+	local i=0
+	set_ifs ", "
+	for p in ${point_type}; do
+	    is_number ${p}
+	    local is=${RETVAL}
+	    if [ "${is}" == "no" ];then
+		echo "ERROR: --pnttype ${point_type}: ${p} must be a number!"
+		exit 1
+	    fi
+	    point_type_array[${i}]=${p}
+	    i=$(($i + 1))
+	done
+	reset_ifs
+    fi
+}
 
+
+parse_linetype()
+{
+    if [ "${line_type}" != "" ];then
+	local lt
+	local i=0
+	set_ifs ", "
+	for lt in ${line_type}; do
+	    is_number ${lt}
+	    local is=${RETVAL}
+	    if [ "${is}" == "no" ];then
+		echo "ERROR: --linetype ${line_type}: ${lt} must be a number!"
+		exit 1
+	    fi
+	    line_type_array[${i}]=${lt}
+	    i=$(($i + 1))
+	done
+	reset_ifs
+    fi
+}
 
 parse_xavg()
 {
@@ -2007,7 +2057,7 @@ parse_arguments()
     local long_args="help,bar,hmap,line,stack,dir:,xvals:,yvals:,zvals:,filter:,\
 title:,xlabel:,ylabel:,data:,xtags:,ytags:,ztags:,xnorm:,ynorm:,ynormv:,xrotate:,\
 legend:,size:,xformat:,yformat:,ytics:,yrange:,colors:,ignore,gap:,xmask:,ymask:,\
-zmask:,xavg:,yavg:,percent,barw:,linew:,pntsize:,barlw:,noviewer,viewer:,xlabeloffset:,\
+zmask:,xavg:,yavg:,percent,barw:,linew:,linetype:,pntsize:,pnttype:,barlw:,noviewer,viewer:,xlabeloffset:,\
 ylabeloffset:,ztagsoffset:,gp:,out:,zlabel:,noappend,outformat:,version"
     local args=`getopt -o "${short_args}" -l "${long_args}" -n "getopt.sh" -- "$@"`
     local args_array=($args)
@@ -2065,7 +2115,9 @@ ylabeloffset:,ztagsoffset:,gp:,out:,zlabel:,noappend,outformat:,version"
 	    "--percent"|"-percent") percent="YES";;
 	    "--barw"|"-barw") bar_width="$2";shift;;
 	    "--linew"|"-linew") line_width="$2";shift;;
+	    "--linetype"|"-linetype") line_type="$2";shift;;
 	    "--pntsize"|"-pntsize") point_size="$2";shift;;
+	    "--pnttype"|"-pnttype") point_type="$2";shift;;
 	    "--barlw"|"-barlw") bar_line_width="$2";shift;;
 	    "--noviewer"|"-noviewer") no_viewer="YES";;
 	    "--viewer"|"-viewer") eps_viewer="$2";shift;;
@@ -2134,6 +2186,12 @@ ylabeloffset:,ztagsoffset:,gp:,out:,zlabel:,noappend,outformat:,version"
     if [ $? -ne 0 ]; then exit 1; fi
 
     parse_ymask
+    if [ $? -ne 0 ]; then exit 1; fi
+
+    parse_linetype
+    if [ $? -ne 0 ]; then exit 1; fi
+
+    parse_pnttype
     if [ $? -ne 0 ]; then exit 1; fi
 
     parse_xavg
@@ -2238,7 +2296,9 @@ ylabeloffset:,ztagsoffset:,gp:,out:,zlabel:,noappend,outformat:,version"
     echo "| percent: ${percent}"
     echo "| bar width: ${bar_width}"
     echo "| line width: ${line_width}"
+    echo "| line type: ${line_type}"
     echo "| point size: ${point_size}"
+    echo "| point type: ${point_type}"
     echo "| bar line width: ${bar_line_width}"
     echo "| .data file: ${data_file}"
     echo "| .gp   file: ${gpfname}"
@@ -2308,7 +2368,9 @@ usage()
     echo "   --viewer <file viewer>       : (Opt) Prefer to use VIEWER."
     echo "   --barw <bar width>           : (Opt) Set the bar width."
     echo "   --linew <line width>         : (Opt) Set the line width."
+    echo "   --linetype <3,6,1,...>       : (Opt) Set the line type."
     echo "   --pntsize <point size>       : (Opt) Set the line point size."
+    echo "   --pnttype <3,6,1,...>        : (Opt) Set the line point types."
     echo "   --barlw <bar line width>     : (Opt) Set the bar line width."
     echo "   --noappend                   : (Opt) Dont append moufoplot data to eps."
     echo "   --outformat <eps|png|jpeg>   : (Opt) Select output file format."
@@ -2327,9 +2389,9 @@ append_data_to_eps()
 	return
     fi
     echo "Appending moufoplot command to ${epsfile}..."
-    echo "%%%%%%%%%%%%%%%%%%%%%" >> ${epsfile}
-    echo "%% moufoplot command:" >> ${epsfile}
-    echo "%%%%%%%%%%%%%%%%%%%%%" >> ${epsfile}
+    echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> ${epsfile}
+    echo "%% `version` , `gnuplot --version`" >> ${epsfile}
+    echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> ${epsfile}
     # echo $@ | sed 's/^/%% /' >> ${epsfile}
     echo "moufoplot ${arguments_saved}" | sed 's/^/%% /' >> ${epsfile}
 
